services:
  optimum-habana:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-vault.habana.ai/gaudi-docker/1.16.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.2}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-latest}
        GAUDI_SW_VER: 1.16.1
        OPTIMUM_HABANA_VER: 1.12.0
        REGISTRY: ${REGISTRY}
        REPO: ${REPO}
      context: .
      labels:
        org.opencontainers.base.name: "${BASE_IMAGE_NAME:-vault.habana.ai/gaudi-docker/1.16.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.2}:${BASE_IMAGE_TAG:-latest}" 
        org.opencontainers.image.title: "Optimum for Intel速 Gaudi速 Accelerators"
        org.opencontainers.image.version: gaudi-${GAUDI_SW_VER:-1.16.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.12.0}
    command: >
      sh -c "python -c 'from optimum import habana; print(\"optimum-habana:\", habana.__version__)'"
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-gaudi-${GAUDI_SW_VER:-1.16.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.12.0}
    pull_policy: always
  optimum-habana-examples:
    build:
      labels:
        org.opencontainers.base.name: "${REGISTRY}/${REPO}:gaudi-${GAUDI_SW_VER:-1.16.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.12.0}"
        org.opencontainers.image.title: "Optimum for Intel速 Gaudi速 Accelerators Examples"
        org.opencontainers.image.version: gaudi-${GAUDI_SW_VER:-1.16.1}-optimum-habana-examples-${OPTIMUM_HABANA_VER:-1.12.0}
      target: optimum-habana-examples
    command: >
      sh -c "python -c 'from optimum import habana; print(\"optimum-habana:\", habana.__version__)'"
    extends: optimum-habana
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-gaudi-${GAUDI_SW_VER:-1.16.1}-optimum-habana-examples-${OPTIMUM_HABANA_VER:-1.12.0}

