services:
  optimum-habana:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:-vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-latest}
        GAUDI_SW_VER: 1.15.1
        OPTIMUM_HABANA_VER: 1.11.1
        REGISTRY: ${REGISTRY}
        REPO: ${REPO}
      context: .
      labels:
        org.opencontainers.base.name: "vault.habana.ai/gaudi-docker/1.15.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest"
        org.opencontainers.image.name: "intel/ai-workflows"
        org.opencontainers.image.title: "Optimum for Intel速 Gaudi速 Accelerators"
        org.opencontainers.image.version: gaudi-${GAUDI_SW_VER:-1.15.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.11.1}
    command: >
      sh -c "python -c 'from optimum import habana; print(\"optimum-habana:\", habana.__version__)'"
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-gaudi-${GAUDI_SW_VER:-1.15.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.11.1}
    pull_policy: always
  optimum-habana-examples:
    build:
      labels:
        org.opencontainers.base.name: "intel/ai-workflows:gaudi-${GAUDI_SW_VER:-1.15.1}-optimum-habana-${OPTIMUM_HABANA_VER:-1.11.1}"
        org.opencontainers.image.title: "Optimum for Intel速 Gaudi速 Accelerators Examples"
        org.opencontainers.image.version: gaudi-${GAUDI_SW_VER:-1.15.1}-optimum-habana-examples-${OPTIMUM_HABANA_VER:-1.11.1}
      target: optimum-habana-examples
    command: >
      sh -c "python -c 'from optimum import habana; print(\"optimum-habana:\", habana.__version__)'"
    extends: optimum-habana
    image: ${REGISTRY}/${REPO}:b-${GITHUB_RUN_NUMBER:-0}-gaudi-${GAUDI_SW_VER:-1.15.1}-optimum-habana-examples-${OPTIMUM_HABANA_VER:-1.11.1}
